# Funding Functions with NumPy and Jupyter

NumPy is a large complex library with hundreds of useful functions. Often the hardest part of solving a problem with NumPy is simply finding the right function to use, or figuring out whether a function you've found can solve your problem.

The official documentation for Numpy and SciPy are excellent resources:

- The official NumPy documentation: [https://docs.scipy.org/doc/numpy-1.13.0/reference/](https://docs.scipy.org/doc/numpy-1.13.0/reference/)
- The offical SciPy documentation: [https://docs.scipy.org/doc/scipy/reference/](https://docs.scipy.org/doc/scipy/reference/)

There are also a few tricks you can use to learn about NumPy functions without having to leave the notebook:

In [1]:
import numpy as np

Suppose, for example, that we want to find the [eigenvalues](https://en.wikipedia.org/wiki/Eigenvalues_and_eigenvectors) of a matrix. The first thing we might try is to use Jupyter's tab-completion feature to see if there's a top-level function:

In [2]:
# Place your cursor immediately after the `e` and hit TAB to see the top-level numpy functions
# that start with the letter "e"
np.e
print("mona")

mona


Unfortunately for us, none of the functions that appear look like they're related to eigenvalues. The next thing we can try is to use [`np.lookfor`](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.lookfor.html) to search for "eigenvalue" by keyword:

In [3]:
np.lookfor("eigenvalue")

Search results for 'eigenvalue'
-------------------------------
numpy.linalg.eig
    Compute the eigenvalues and right eigenvectors of a square array.
numpy.linalg.eigh
    Return the eigenvalues and eigenvectors of a Hermitian or symmetric matrix.
numpy.linalg.eigvals
    Compute the eigenvalues of a general matrix.
numpy.linalg.eigvalsh
    Compute the eigenvalues of a Hermitian or real symmetric matrix.
numpy.roots
    Return the roots of a polynomial with coefficients given in p.
numpy.linalg.svd
    Singular Value Decomposition.
numpy.linalg._umath_linalg.eig
    eig on the last two dimension and broadcast to the rest.
numpy.polynomial.Hermite._roots
    Compute the roots of a Hermite series.
numpy.polynomial.HermiteE._roots
    Compute the roots of a HermiteE series.
numpy.polynomial.Laguerre._roots
    Compute the roots of a Laguerre series.
numpy.polynomial.Legendre._roots
    Compute the roots of a Legendre series.
numpy.polynomial.Chebyshev._roots
    Compute the roots of a C

That looks more promising, but now we have to figure out which function to use. For that, we can use Jupyter's `?` operator to look up the documentation for any function we're interested in.

In [6]:
np.linalg.eigvals?

For cases where we just to check a docstring quickly, it can be more ergonomic to bring up documentation in-line using Shift+Tab:

Place your cursor after "eigvals", hold Shift, and then press Tab. You should see the signature and the first line of the function's documentation. You can see the rest of the documentation by pressing Tab again without letting go of Shift.

In [8]:
np.linalg.eigvals

<function numpy.linalg.linalg.eigvals(a)>

## Exercise: Finding Functions

Use `np.lookfor` and `?` to find functions that do the following:

- Compute the largest value in an array.
- Compute the smallest value in an array.
- Compute the value at the 90th percentile of an array.
- Sort an array.
- Find a value in a sorted array.
- Compute the [natural logarithm](https://en.wikipedia.org/wiki/Natural_logarithm) of each element in an array.
- Compute the [Correlation Coefficient](https://en.wikipedia.org/wiki/Correlation_coefficient) between two arrays.
- Fit coefficients of a polynomial function.
- Compute a [Covariance Matrix](https://en.wikipedia.org/wiki/Covariance_matrix).

In [9]:
np.lookfor("max")

Search results for 'max'
------------------------
numpy.amax
    Return the maximum of an array or maximum along an axis.
numpy.fmax
    Element-wise maximum of array elements.
numpy.argmax
    Returns the indices of the maximum values along an axis.
numpy.nanmax
    Return the maximum of an array or maximum along an axis, ignoring any
numpy.maximum
    Element-wise maximum of array elements.
numpy.nanargmax
    Return the indices of the maximum values in the specified axis ignoring
numpy.ptp
    Range of values (maximum - minimum) along an axis.
numpy.ma.max
    Return the maximum along a given axis.
numpy.ma.argmax
    Returns array of indices of the maximum values along the given axis.
numpy.ma.maximum
    Object to calculate maxima
numpy.matrix.max
    Return the maximum value along an axis.
numpy.chararray.max
    Return the maximum along a given axis.
numpy.ma.ptp
    Return (maximum - minimum) along the given dimension
numpy.matrix.argmax
    Indexes of the maximum values along 

In [10]:
np.lookfor("min")

Search results for 'min'
------------------------
numpy.amin
    Return the minimum of an array or minimum along an axis.
numpy.fmin
    Element-wise minimum of array elements.
numpy.argmin
    Returns the indices of the minimum values along an axis.
numpy.nanmin
    Return minimum of an array or minimum along an axis, ignoring any NaNs.
numpy.hamming
    Return the Hamming window.
numpy.minimum
    Element-wise minimum of array elements.
numpy.nanargmin
    Return the indices of the minimum values in the specified axis ignoring
numpy.ptp
    Range of values (maximum - minimum) along an axis.
numpy.array
    Create an array.
numpy.mintypecode
    Return the character for the minimum-size type to which given types can
numpy.ma.min
    Return the minimum along a given axis.
numpy.bincount
    Count number of occurrences of each value in array of non-negative ints.
numpy.issctype
    Determines whether the given object represents a scalar data-type.
numpy.ma.argmin
    Return array of ind

In [11]:
np.lookfor("percentile")

Search results for 'percentile'
-------------------------------
numpy.percentile
    Compute the qth percentile of the data along the specified axis.
numpy.nanpercentile
    Compute the qth percentile of the data along the specified axis,
numpy.median
    Compute the median along the specified axis.
numpy.nanmedian
    Compute the median along the specified axis, while ignoring NaNs.


In [12]:
np.lookfor("sort")

Search results for 'sort'
-------------------------
numpy.sort
    Return a sorted copy of an array.
numpy.msort
    Return a copy of an array sorted along the first axis.
numpy.argsort
    Returns the indices that would sort an array.
numpy.lexsort
    Perform an indirect sort using a sequence of keys.
numpy.searchsorted
    Find indices where elements should be inserted to maintain order.
numpy.sort_complex
    Sort a complex array using the real part first, then the imaginary part.
numpy.unique
    Find the unique elements of an array.
numpy.ma.sort
    Sort the array, in-place
numpy.union1d
    Find the union of two arrays.
numpy.setxor1d
    Find the set exclusive-or of two arrays.
numpy.ma.argsort
    Return an ndarray of indices that sort the array along the
numpy.setdiff1d
    Find the set difference of two arrays.
numpy.intersect1d
    Find the intersection of two arrays.
numpy.chararray.sort
    Sort an array, in-place.
numpy.matrix.argsort
    Returns the indices that would 

In [13]:
np.lookfor("find")

Search results for 'find'
-------------------------
numpy.poly
    Find the coefficients of a polynomial with the given sequence of roots.
numpy.unique
    Find the unique elements of an array.
numpy.polyadd
    Find the sum of two polynomials.
numpy.polymul
    Find the product of two polynomials.
numpy.union1d
    Find the union of two arrays.
numpy.argwhere
    Find the indices of array elements that are non-zero, grouped by element.
numpy.bytes0.find
    Return the lowest index in B where subsection sub is found,
numpy.setxor1d
    Find the set exclusive-or of two arrays.
numpy.str0.find
    Return the lowest index in S where substring sub is found,
numpy.bytes0.rfind
    Return the highest index in B where subsection sub is found,
numpy.setdiff1d
    Find the set difference of two arrays.
numpy.str0.rfind
    Return the highest index in S where substring sub is found,
numpy.intersect1d
    Find the intersection of two arrays.
numpy.searchsorted
    Find indices where elements shou

In [14]:
np.lookfor('log')

Search results for 'log'
------------------------
numpy.log
    Natural logarithm, element-wise.
numpy.log2
    Base-2 logarithm of `x`.
numpy.log10
    Return the base 10 logarithm of the input array, element-wise.
numpy.log1p
    Return the natural logarithm of one plus the input array, element-wise.
numpy.logspace
    Return numbers spaced evenly on a log scale.
numpy.logaddexp
    Logarithm of the sum of exponentiations of the inputs.
numpy.logaddexp2
    Logarithm of the sum of exponentiations of the inputs in base-2.
numpy.logical_or
    Compute the truth value of x1 OR x2 element-wise.
numpy.logical_and
    Compute the truth value of x1 AND x2 element-wise.
numpy.logical_not
    Compute the truth value of NOT x element-wise.
numpy.logical_xor
    Compute the truth value of x1 XOR x2, element-wise.
numpy.ma.log
    Natural logarithm, element-wise.
numpy.ma.log2
    Base-2 logarithm of `x`.
numpy.ma.log10
    Return the base 10 logarithm of the input array, element-wise.
numpy.rec

In [15]:
np.lookfor('correlation')

Search results for 'correlation'
--------------------------------
numpy.corrcoef
    Return Pearson product-moment correlation coefficients.
numpy.correlate
    Cross-correlation of two 1-dimensional sequences.
numpy.ma.corrcoef
    Return Pearson product-moment correlation coefficients.
numpy.ma.correlate
    Cross-correlation of two 1-dimensional sequences.
numpy.cov
    Estimate a covariance matrix, given data and weights.
numpy.vectorize
    vectorize(pyfunc, otypes=None, doc=None, excluded=None, cache=False,


In [16]:
np.lookfor("polynomial fit")

Search results for 'polynomial fit'
-----------------------------------
numpy.polyfit
    Least squares polynomial fit.
numpy.ma.polyfit
    Least squares polynomial fit.
numpy.polynomial.Polynomial._fit
    Least-squares fit of a polynomial to data.
numpy.poly
    Find the coefficients of a polynomial with the given sequence of roots.
numpy.roots
    Return the roots of a polynomial with coefficients given in p.
numpy.polyadd
    Find the sum of two polynomials.
numpy.polydiv
    Returns the quotient and remainder of polynomial division.
numpy.polymul
    Find the product of two polynomials.
numpy.polynomial.Hermite.fit
    Least squares fit to data.
numpy.polynomial.Hermite._fit
    Least squares fit of Hermite series to data.
numpy.polynomial.HermiteE.fit
    Least squares fit to data.
numpy.polynomial.Laguerre.fit
    Least squares fit to data.
numpy.polynomial.Legendre.fit
    Least squares fit to data.
numpy.polynomial.Chebyshev.fit
    Least squares fit to data.
numpy.polynomial

In [17]:
np.lookfor("covariance matrix")

Search results for 'covariance matrix'
--------------------------------------
numpy.cov
    Estimate a covariance matrix, given data and weights.
numpy.ma.cov
    Estimate the covariance matrix.
numpy.polyfit
    Least squares polynomial fit.
numpy.corrcoef
    Return Pearson product-moment correlation coefficients.
numpy.ma.polyfit
    Least squares polynomial fit.
numpy.ma.corrcoef
    Return Pearson product-moment correlation coefficients.


In [21]:
n=10
p=0.5
np.random.binomial(n, p, 100)

array([3, 5, 4, 5, 4, 4, 2, 7, 5, 5, 4, 4, 4, 8, 5, 7, 5, 5, 6, 5, 4, 5, 1,
       3, 3, 5, 5, 1, 3, 6, 4, 6, 4, 6, 5, 3, 6, 8, 5, 8, 5, 8, 6, 5, 5, 3,
       6, 8, 3, 5, 4, 3, 4, 6, 4, 6, 4, 3, 6, 4, 8, 5, 8, 4, 5, 4, 4, 4, 5,
       5, 3, 6, 6, 3, 5, 5, 4, 5, 3, 4, 8, 6, 4, 6, 3, 3, 4, 4, 7, 5, 5, 3,
       4, 5, 6, 5, 4, 6, 7, 4])

In [22]:
m = np.linspace(-5, 5, 9)

In [23]:
m

array([-5.  , -3.75, -2.5 , -1.25,  0.  ,  1.25,  2.5 ,  3.75,  5.  ])

In [24]:
data = m.reshape(3, 3)

In [25]:
data

array([[-5.  , -3.75, -2.5 ],
       [-1.25,  0.  ,  1.25],
       [ 2.5 ,  3.75,  5.  ]])

In [26]:
np.where(data>0, data, -data)

array([[ 5.  ,  3.75,  2.5 ],
       [ 1.25, -0.  ,  1.25],
       [ 2.5 ,  3.75,  5.  ]])

In [29]:
#not to get -0
np.where(data>0, data, -data) #vectorized if statement

array([[ 5.  ,  3.75,  2.5 ],
       [ 1.25, -0.  ,  1.25],
       [ 2.5 ,  3.75,  5.  ]])