# Selections

Often when we're working with numpy we're only interested in a portion of the data in our arrays. The `[]` on `ndarray` allows us select portions of the data in the array in a variety of interesting ways.

The exercises in this notebook will teach you how to select elements out of arrays in a variety of ways.

In [1]:
import numpy as np

rand = np.random.RandomState(42)  # Use a deterministic seed.

## Exercise: 1-dimensional selection

Write expressions to select the following elements from the array:

1. first element
1. second element
1. last element
1. second to last element
1. first 5 elements
1. last 5 elements
1. elements at indices 1, 4, 7, and 13
1. every other element
1. the entire array, in reverse order
1. every other element, starting at index 3 (inclusive) ending at index 17 (exclusive)

In [5]:
array = np.arange(20)

In [6]:
array[0]

0

In [7]:
array[1]

1

In [8]:
array[-1]

19

In [9]:
array[:5]

array([0, 1, 2, 3, 4])

In [11]:
array[-5:]

array([15, 16, 17, 18, 19])

In [13]:
array[[1, 4, 7, 13]]

array([ 1,  4,  7, 13])

In [18]:
array[::2] 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [19]:
array[: : -1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0])

In [21]:
array[3:17:2]

array([ 3,  5,  7,  9, 11, 13, 15])

## Exercise: 2-dimensional selection

Write expressions to select the following elements from the array.

1. scalar value at coordinates `[3, 6]`
1. top-left scalar value
1. first row
1. first column
1. second column
1. last column
1. first 5 columns
1. last 5 columns
1. top-left 2 x 2 square
1. top-right 2 x 2 square
1. last 5 rows from every other column

In [26]:
array = np.arange(20 * 20).reshape(20, 20)

In [27]:
array[3, 6]

66

In [28]:
array[0, 0]

0

In [29]:
array[0:]

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32,
         33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
         53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,
         73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
         93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
        113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132,
        133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152,
        153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 1

## Exercise: Selections with boolean arrays.

In [ ]:
array = rand.normal(0, 1, 50)

Write an expression to select the positive values from the array.

Write an expression to select the values less than -1 **or** greater than 1.5.

In [ ]:
array = rand.normal(0, 1, 50)

Write an expression that produces the value from `array` if the value is positive, and produces the **square** of the value if it's negative.

In [ ]:
np.where?

## Exercise: "FizzBuzz"

Write an expression that converts `array` into a new array of the same shape according to the following rules:

At each index `[i]`

- if `array[i]` is divisible by 3: `result[i]` should hold -1
- if `array[i]` is divisible by 5: `result[i]` should hold -2
- if `array[i]` is divisible by 15, `result[i]` should hold -3
- otherwise:`result[i]` should hold `array[i]`

In [ ]:
array = np.arange(1, 100)
np.select?

## Exercise: N-dimensional FizzBuzz

Same rules as above, but on a 3-dimensional array. (HINT: If you did the previous exercise idiomatically, you shouldn't need to change anything).

In [37]:
array = np.arange(1, 101).reshape(5, 20)
array

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,
         34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,
         54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,
         74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,
         94,  95,  96,  97,  98,  99, 100]])

In [38]:
array.mean()

50.5

In [39]:
array.mean(axis=0)

array([ 41.,  42.,  43.,  44.,  45.,  46.,  47.,  48.,  49.,  50.,  51.,
        52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.,  60.])

In [40]:
array.mean(axis=1)

array([ 10.5,  30.5,  50.5,  70.5,  90.5])

In [41]:
np.count_nonzero(array)

100

In [42]:
np.max(array)

100

In [43]:
np.min(array)

1

In [44]:
np.var(array)

833.25

In [45]:
np.median(array)

50.5